### ISSUE TITLE
Features content

### ISSUE THREAD

**Issue by StefanPuia** [neanmi/website#24]
```json
{
  "header": "Elit qui occaecat est do labore magna dolor voluptate do laboris.",
  "subheader": "Ut cupidatat do consectetur ad laboris incididunt excepteur."
}
```

For each feature:
```yml
key: feature1
title: Feature 1
description: Veniam laboris ex proident reprehenderit laboris occaecat sit aliquip cillum pariatur.
image: https://picsum.photos/seed/b/300/180
```
