### ISSUE TITLE
Services content

### ISSUE THREAD

**Issue by StefanPuia** [neanmi/website#25]
For each service
```yml
key: devops
title: DevOps
description: DevOps In culpa ad ex aliquip nulla commodo cillum tempor officia aliqua.
image: https://picsum.photos/seed/a/300
icon: solid fa-wrench
```
